
const data = [
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Ruso",
    },
    {
        name:"Artur",
        lastName:"Garaev",
        dateOfBirth:"01-05-1978",
        maritalStatus:"Soltero",
        nationality: "Rusode",
    },
];

export default data;